jenkins:
  systemMessage: "JCasC Settings"
  numExecutors: 1
  scmCheckoutRetryCount: 4
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin