---

- name: Install pip3
  apt:
    update_cache: yes
    pkg:
      - python-setuptools
      - python3-pip

- name: Install Docker module for Python 3
  pip:
    executable: pip3
    name: docker

- name: Pull Jenkins image
  docker_image:
    name: "{{ jenkins_image }}"
    state: present

- name: Create Jenkins container
  docker_container:
#   docker_host: unix://var/run/docker.sock
    detach: yes
    name: Jenkins_server
    image: "{{ jenkins_image }}" 
    state: started
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home


