---

- name: Install pip3
  apt:
    update_cache: yes
    pkg:
      - python-setuptools
      - python3-pip

- name: Install Docker module for Python 3
  pip:
    executable: pip3
    name: docker

- name: pull Jenkins image
  docker_image:
    name: jenkins/jenkins
    state: present
